openapi: 3.0.1
info:
  title: Residential Sales and Rental HDB (SG)
  description:  This Data microservice retreives comprehensive details of each HDB block in Singapore including the number of units for each type of flats and whether they were sold or leased. Queries based on keywords and proximity to particular locations can be performed. Updated weekly.<br><br><b>Authentication</b>:<br><br>Authentication is done using the x-api-key in the request header.<br><h3><b>Search Types</b></h3><br>*All values have to be URL encoded<br><br><b>Keyword search</b><br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Keyword search; search for all searchable fields<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Using querystring:<br><br><div style="padding-left:22px;"><i>ang mo kio</i></div><br><b>Filter search</b><br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Example 1:</b> Get all results except ang mo kio <br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Using fiterdata:<br><br><div style="padding-left:22px;"><i>{"must_not":[{"match_phrase":{"street":"ang mo kio"}}]}</i></div><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Or<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Using querystring:<br><br><div style="padding-left:22px;"><i>name:"ang mo kio"</i></div><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Example 2:</b> Filter results with branch office AM<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Using fiterdata:<br><br><div style="padding-left:22px;"><i>{"filter":[{"match":{"year_completed":"1999"}}]}</i></div><br><h3><b>Supported Filter Types:</b></h3><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>must</b> - All of these clauses must match. The equivalent of AND.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>must_not</b> - All of these clauses must not match. The equivalent of NOT.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>should</b> - At least one of these clauses must match. The equivalent of OR.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>filter</b> - Clauses that must match, but are run in non-scoring, filtering mode.<br><br><h3><b>Supported Match Types:</b></h3><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>match</b> - is to search within a full-text field for a single word<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{ "match":{"street":"bishan"}}<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>match_phrase</b> - is to search a full text field<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{ "match_phrase":{ "street":bishan street 24"}}<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>match_phrase_prefix</b> - is to search a full text field with prefix<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{"match_phrase_prefix":{"street":"bishan"}}<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>term</b> - returns documents that contain one or more exact terms in a provided field.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{"term":{"street":"bishan"}}<br><br><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;terms</b> - The terms query is the same as the term query, except you can search for multiple values.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{"terms":{"street":["bishan","and mo kio"]}}<br><br><h3><b>Sample filterdata JSON:</b></h3><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"must":[{"match_phrase":{"street":"ang+mo+kio+street+21"}}],<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"filter":[{"match":{"tags.type":"source"}}] ,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"should":[{"match":{"source":"hdb"}}],<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"must_not":[{"match":{"postalcode":"750353"}}<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
  version: '0.1'
servers:
  - url: 'https://api.sentient.io'
tags:
- name: "v0.1"
  description: "Published Date - Oct 10, 2019"
paths:
   /DaaS/prod/hdb/buildinginfo:
    get:
      tags:
        - v0.1
      parameters:
        - in: query
          name: querystring
          schema:
            type: string
          description: keyword match to all searchable fields
          required: true
        - in: query
          name: offset
          schema:
            type: integer
          description: The offset of the record list ie the starting index
          required: false
        - in: query
          name: limit
          schema:
            type: integer
          description: The max records to return for the request
          required: false
        - in: query
          name: filterdata
          schema:
            type: string
          description: Additional filter {"must":[ ],"should":[ ],"must_not":[ ],"filter":[ ]}
          required: false
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties:
        results:
          type: object
          properties:
            total:
              type: number
              example: 12150
              description: Total number of records
            max_score:
              type: number
              example: 1
              description: The highest score value
            hits:
              type: array
              items:
                type: object
                properties:
                  _index: 
                    type: string
                    description: Index of the document
                    example: "sentient_buildinginfo_hdb_index"
                  _type:
                    type: string
                    description: Content type of the document
                    example: dir_doc
                  _id:  
                    type: string
                    description: Document ID
                    example: '750405'
                  _score: 
                    type: string
                    description: The document score for the search request
                    example: 1
                  _source:
                    properties:
                      postalcode:
                        type: string
                        description: Postal code
                        example: '750405'
                      year_completed:
                        type: string
                        description: Total completed year of the Building
                        example: 1999
                      total_dwelling_units:
                        type: string
                        description: Total Dwelling units
                        example: 112
                      1room_sold: 
                        type: string
                        description: No. of one room units sold
                        example: 0
                      2room_sold: 
                        type: string
                        description: No. of two room units sold
                        example: 0
                      3room_sold:
                        type: string
                        description: No. of three room units sold
                        example: 0
                      4room_sold: 
                        type: string
                        description: No. of four room units sold
                        example: 112
                      5room_sold: 
                        type: string
                        description: No. of five room units sold
                        example: 0
                      exec_sold: 
                        type: string
                        description: No. of executive units sold
                        example: 0
                      multigen_sold: 
                        type: string
                        description: No. of multi generation units sold
                        example: 0
                      studio_apartment_sold: 
                        type: string
                        description: No. of studio units sold
                        example: 0
                      1room_rental:
                        type: string
                        description: No. of one room units rented
                        example: 0
                      2room_rental: 
                        type: string
                        description: No. of two room units rented
                        example: 0
                      3room_rental: 
                        type: string
                        description: No. of three room units rented
                        example: 0
                      other_room_rental: 
                        type: string
                        description: No. of other units rented
                        example: 0
                      block:
                        type: string
                        description: Shop block
                        example: 405
                      street: 
                        type: string
                        description: Shop street
                        example: ADMIRALTY LINK
                      xcoord: 
                        type: string
                        description: SVY21 X coordinates
                        example: 26086.0996
                      ycoord: 
                        type: string
                        description: SVY21 Y coordinates
                        example: 48325.8008
                      address: 
                        type: string
                        description: Shop full address
                        example: 405 ADMIRALTY LINK
                      createddate: 
                        type: string
                        description: Record first release date on sentient
                        example: '2019-10-17'
                      lastupdated: 
                        type: string
                        description: Record last updated date on sentient
                        example: '2019-10-17'
                      location:
                        properties:
                            lat: 
                              type: string
                              description: WGS84 latitude
                              example: 1.37179535
                            lon:
                              type: string
                              description: WGS84 longitude
                              example: 103.8469821
                      source: 
                        type: string
                        description: Index group of the document
                        example: hdb
        message:
          type: string
          example: Successfully Processed
        status:
          type: string
          example: Success
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure      
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom