openapi: 3.0.1
info:
  title: Inverse Text Normalisation ENG
  description: >-
    This NLP microservice recovers the missing punctuations such as full stop, comma, exclamation mark, and question mark from the input text.<br><br>This NLP microservice also converts pre-defined abbreviations from lower case to upper case.<br><br>This NLP microservice also converts first letters of sentences to upper case."<br><br><b>Authentication</b>:<br><br>Authentication is done using the x-api-key in the request header.
  version: '0.1'
servers:
  - url: 'https://apis.sentient.io'
tags:
- name: "v0.1"
  description: "Published Date - Mar 02, 2020"
paths:
  /microservices/nlp/inversenorm/v0.1/getpredictions:
    post:
      tags:
        - v0.1
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        description: <b>Input parameters</b><br><br><table class="inputtable" style="width:100%;border:1px solid grey"><tr><th style="width:15%;"><b>Field</b></th><th style="width:15%;"><b>Type</b></th><th style="width:70%;"><b>Description</b></th></tr><tr><td><b>text</b></td><td>String</td><td>Required. A sentence</td></tr><tr><td><b>start</b></td><td>Float</td><td>Required. Start time</td></tr><tr><td><b>end</b></td><td>Float</td><td>Required. End time</td></tr><tr><td><b>seqNum</b></td><td>Integer</td><td>Required. Text order ID</td></tr></table><br><br>
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        0:
          type: string
          example: Apple said, the project-financing fund was the 1 of its kind, real estate developers, often secure bonds for affordable housing development, but must service the debt during construction, until the houses are built and start to generate revenue, apple and state officials hope to provide bridge financing during construction at rates below those from commercial lenders.
        1:
          type: string
          example: The $2000000000 in funding will be deployable across NTU while the remaining 5500000000 will go toward efforts specific to apple's home region in northern california, where fast-growing tech companies have drawn protests from residents who blame them for rising, housing costs.
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure      
    input:
      type: array
      items:
        properties:
          text:
              type: string
              example: Apple said the project-financing fund was the first of its kind Real estate developers often secure bonds for affordable housing development but must service the debt during construction until the houses are built and start to generate revenue Apple and state officials hope to provide bridge financing during construction at rates below those from commercial lenders
          start:
            type: string
            format: float
            example: 20.44
          end:
            type: string
            format: float
            example: 28.4
          seqNum:
            type: integer
            example: 4
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom