
openapi: 3.0.1
info:
  title: Sentence Scoring
  description: |+
    To compute the probability of each word in a sentence and generate suggested words. The input is a single sentence 
  version: v0.1.0
  x-subscribelink: sentence_scoring
servers:
  - url: 'https://dev-apis.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - Oct 05, 2021"
paths:
  /microservices/nlp/sentencescoring/v0/getpredictions:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                results: 
                  result:
                  - conf: 0.012762350961565971
                    top_k:
                      where: 0.7936621904373169
                      who: 0.14036813378334045
                    word: how
                  - conf: 0.024699058383703232
                    top_k:
                      can: 0.10830813646316528
                      could: 0.7056182026863098
                    word: are
                  - conf: 0.0003625013923738152
                    top_k:
                      .: 0.029543984681367874
                      '?': 0.9645142555236816
                    word: you
                  text: how are you

                message: Successfully Processed
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'       
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        results:
          type: object
          description: The result of the API call.
          example: { "<Json": "Object>" }
          properties: 
            result:
              description: Array of dictionaries, each dictionary containing a word from the input text and its probability
              example:
                conf: 0.1
                word: how
              items:
                oneOf:
                  - properties:
                      conf:
                        description: The probability of the word in the input text
                        example: 0.1
                        type: float
                      word:
                        description: The word in the input text
                        example: how
                        type: string
                      top_k:
                        description: The dictionary of suggested words
                        example: {"where": 0.7936621904373169,"who": 0.14036813378334045}
                        type: object
                    type: object
              type: array
            text:
              description: Input text
              example: how are you
              type: string

        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
        
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - Oct 05, 2021
                description: Initial version release     
    input:
      type: object
      required:
      
        - text
        - top_k
      properties:
        text:
          x-name: text
          type: string
          default: True
          example: how are you
          description: |+
            Input text
        
        top_k:
          x-name: top_k
          type: number
          default: True
          example: 2
          description: |+
            Number of suggested words to be provided by the model.
        
        
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
