openapi: 3.0.1
info:
  title: spaCy NER
  description: |+
      This NLP microservice locates and classifies the named-entities classes from input unstructured English text, based on the spaCy model. 

      The named-entity classes extracted include persons, nationalities, religious groups, political groups, buildings and facilities, organisations, geopolitical, locations, products, events, works of art, laws, languages, dates and time, percentages, monetary values, quantities, ordinals and cardinals along with entity start and end positions in the text. 

      This microservice automatically extracts structured information from unstructured text data such as chatlogs, emails, news articles, etc.
      
      Do ensure that your text is **within 5000 characters**.
  x-additionalinfo: |+
    Suggested Use Cases:
    - Can be used to build information extraction or natural language understanding systems, or to pre-process text for deep learning -e.g. tokenization, Parts-of-Speech (PoS) Tagging, Text Classification and Named Entity Recognition.
  version: '2.0.0'
  x-subscribelink: spacy_ner
servers:
  - url: 'https://dev-apis.sentient.io'
tags:
- name: "v2.0.0"
  description: "Published Date - Nov 09, 2021"
paths:
  /microservices/nlp/spacyner/v2/getpredictions:
    post:
      tags:
        - v2.0.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example: {"message": "Successfully Processed","results": {
        "fac": [
            [
                "Changi Airport",
                1,
                3
            ],
            [
                "Changi Airport",
                7,
                9
            ],
            [
                "the first Airport",
                71,
                74
            ]
        ],
        "gpe": [
            [
                "Singapore",
                0,
                1
            ],
            [
                "Singapore",
                31,
                32
            ],
            [
                "Changi",
                109,
                110
            ],
            [
                "Singapore",
                116,
                117
            ],
            [
                "Singapore",
                129,
                130
            ],
            [
                "Singapore",
                162,
                163
            ]
        ],
        "loc": [
            [
                "Asia",
                42,
                43
            ],
            [
                "Marina Bay",
                126,
                128
            ]
        ],
        "org": [
            [
                "ICAO",
                14,
                15
            ],
            [
                "WSSS",
                16,
                17
            ],
            [
                "FAA",
                18,
                19
            ],
            [
                "the World's Best Airport",
                63,
                68
            ],
            [
                "Skytrax",
                69,
                70
            ],
            [
                "Changi Airport Group",
                152,
                155
            ],
            [
                "Jetstar Asia Airways",
                173,
                176
            ],
            [
                "BOC Aviation",
                177,
                179
            ]
        ],
        "quantity": [
            [
                "approximately 20 km",
                118,
                121
            ],
            [
                "5.0 sq mi",
                141,
                144
            ]
        ]},"status": "Success"}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'  
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties: 
        results:
          type: object
          example: { "<Json": "Object>" }
          description: Json Object of returned results
          properties:
            person:
              x-name: person
              type: array
              example: [DONALD TRUMP,Mike Pompeo]
              description: People, including fictional.
        message:
          x-name: message
          type: string
          example: Successfully Processed
          description: Detail description on the API status
          
        status:
          x-name: status
          type: string
          example: Success
          description: The status of the API call success/failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure      
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure  
    versions:
      type: object
      properties: 
        v2.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Nov 09, 2021
              description: Output Format Change  
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Sep 30, 2020
              description: Initial version release    
    input:
      type: object
      required:
        - text
      properties:
        text:
          x-name: text
          type: string
          default: true
          example: "Singapore Changi Airport, commonly known as Changi Airport (IATA: SIN, ICAO: WSSS, FAA LID: SIN), is a major civilian airport that serves Singapore, and is one of the largest transportation hubs in Asia. As one of the world's busiest airports by international passenger and cargo traffic, it is currently rated the World's Best Airport by Skytrax, the first Airport in the world to do so for eight consecutive years.[10][11] It has also been rated as the one of the world's cleanest airports and highly rated international transit airports.[12][13]The airport is located in Changi, at the eastern end of Singapore, approximately 20 km (12 mi)[14] from Marina Bay (Singapore's Downtown Core), on a 13-square-kilometre (5.0 sq mi) site. The airport is operated by Changi Airport Group and it is the home base of Singapore Airlines,[15] Singapore Airlines Cargo,[15] SilkAir,[15] Scoot, Jetstar Asia Airways and BOC Aviation."
          description: |+
            Input text
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
