openapi: 3.0.1
info:
  title: Activate Users
  description: This API provides operations to manage users in your organization. Create a user without a password and recovery question/answer. When the user is activated, an email is sent to the user with an activation token that can be used to complete the activation process. This is the default flow for new user registration using the admistrator user dashboard.
  version: v0.1.0
  x-subscribelink: activate_user
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - Jul 09, 2021"
paths:
  /org/activateusers:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: successfully processed
                results:
                  - id: 1326
                    username: example@sentient.io
                  - id: 1545
                    username: example2@sentient.io
                status: success 
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '415':
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - Jul 09, 2021
                description: Initial version release
    input:
      type: object
      required:
        - user_ids
      properties:
        user_ids:
          x-name: user_ids
          type: integer
          default: True
          example: [1326,1545]
          description: Multiple user ids of the user. Invalid user id will be igonred in the array list.
        
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
