openapi: 3.0.1
info:
  title: Add user
  description: This microservice is used to create a new user
  version: v0.1.0
  x-subscribelink: add_user
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - Jul 09, 2021"
paths:
  /org/adduser:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: successfully processed
                results:
                  id: 2196
                status: success
        '415':
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - Jul 09, 2021
                description: Initial version release
    input:
      type: object
      required:
        - user_name
        - user_password
      properties:
        user_name:
          x-name: user_name
          type: string
          default: True
          example: test@gmail.com
          description: User name of the user
        user_password:
          x-name: user_password
          type: string
          default: True
          example: xxxxxx
          description: User password of the user
        send_email:
          x-name: send_email
          type: string
          example: yes
          description: |+
            User email send option
            - yes - Email send to the user
            - no  - Email will not send to user
        user_groups:
          x-name: user_groups
          type: string
          example: []
          description: User groups list of the user
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
