openapi: 3.0.1
info:
  title: Add Group To User
  description: This microservice is used to add users to group.
  x-subscribelink: add_user_to_group
  version: '0.1.0'
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io'
tags:
- name: "v0.1.0"
  description: "Published Date - May 21, 2021"
paths:
   /org/addusertogroup:
    get:
      tags:
        - v0.1.0
      required:
        - user_id
        - group_id
      parameters:
        - in: query
          name: user_id
          schema:
            type: integer
          required: true
          description: User Id
          example: 1121
        - in: query
          name: group_id
          schema:
            type: integer
          required: true
          description: Group Id
          example: 7
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                status: Success

        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: The detail description on the status
        status:
          type: string
          example: Success
          description: The status of the API call Success/Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v1.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Nov 25,2019
              description: Initial version release          
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header.
