openapi: 3.0.1
info:
  title: API metering  graph by microservice
  description: This microservice is used to view the API metering  graph for microservice.
  version: v0.1.0
  x-subscribelink: api_metering_microservice
servers:
  - url: 'https://dev-microserviceapi-catalog.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - May 12, 2021"
paths:
  /apimeteringbymicroservice:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                activity: 'YES'
                message: Successfully Processed
                performance_per_microservice:
                  - api_result:
                      - message: ''
                        unsuccesscount: 1
                    total_unsuccess_call: 1
                status: Success
                usage_per_microservice:
                  - - '2021-01-27'
                    - 2
                    - 0
                  - - '2021-01-28'
                    - 2
                    - 0
                  - - '2021-02-02'
                    - 4
                    - 0
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        activity:
          type: string
          example: YES
          description: Activity details
        performance_per_microservice:
          type: array
          example: [{<JSON result Object}]
          description: The list of array Json result object
          items:
            type: object
            properties:                      
                api_result:
                  type: array
                  description: The list of Json result object
                  items:
                    type: object
                    properties:
                      message:
                        type: string
                        description: Stauts of the api result
                        example: ""
                      unsuccesscount:
                        type: string
                        description: Unsuccess count of the api
                        example: 1
                total_unsuccess_call:
                  type: string
                  example: 1
                  description: Total unsuccess count of the api
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
        usage_per_microservice:
          type: array
          example: ["2021-01-27",2,0]
          description: The list of Json result object
          items:
            type: object
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - May 12, 2021
                description: Initial version release    
    input:
      type: object
      properties:
        from_date:
          x-name: from_date
          type: string
          default: True
          example: "2021-01-01"
          description: Details from date
        to_date:
          x-name: to_date
          type: string
          default: True
          example: "2021-02-24"
          description: User updated by
        org_id:
          x-name: org_id
          type: integer
          default: True
          example: 1
          description: User updated by
        user_id:
          x-name: user_id
          type: integer
          default: True
          example: 2
          description: User updated by
        function_code:
          x-name: function_code
          type: string
          default: True
          example: WIKIPEDIA
          description: User updated by
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
