openapi: 3.0.1
info:
  title: Delete User
  description: This API provides operations to manage users in your organization. Delete a user and transfer ownership of entities such as alerts, shceduled policies, and workflows from deleted user to another active user or an active user workflow. . When the user is activated, an email is sent to the user with an activation token that can be used to complete the activation process. This is the default flow for new user registration using the admistrator user dashboard.
  x-subscribelink: delete_user_info
  version: '0.1.0'
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io'
tags:
- name: "v0.1.0"
  description: "Published Date - May 21, 2021"
paths:
   /org/deleteuser:
    get:
      tags:
        - v0.1.0
      parameters:
        - in: query
          name: user_id
          schema:
            type: integer
          required: true
          description: User id of the user
          example: 1326
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Deleted
                status: Success
        '415':
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Deleted
          description: The detail description on the status
        status:
          type: string
          example: Success
          description: The status of the API call Success/Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Jul 09,2021
              description: Initial version release          
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header.
