openapi: 3.0.1
info:
  title: Group Info
  description: Get group info
  x-subscribelink: group_info
  version: '1.0.0'
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io'
tags:
- name: "v1.0.0"
  description: "Published Date - May 21, 2021"
paths:
   /org/getgroupinfo:
    get:
      tags:
        - v1.0.0
      parameters:
        - in: query
          name: group_id
          schema:
            type: integer
          description: Group Id
          example: 253
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: ''
                result:
                  created_by: ''
                  date_created: 10 jul 2019 / 08:48
                  date_updated: 10 jul 2019 / 08:48
                  group_description: Default Consumer Group
                  group_function:
                    - id: 4574
                      value: Market Place Screen
                    - id: 4575
                      value: My Contract Screen
                    - id: 4576
                      value: Add Contract
                    - id: 4577
                      value: Update Contract
                    - id: 4578
                      value: Market Place
                    - id: 4579
                      value: Contract List
                    - id: 4580
                      value: Contract History
                    - id: 4581
                      value: Transactions screen
                  group_name: TEST M3 Consumer Group
                  id: 253
                  users:
                    - id: 337
                      value: root210
                    - id: 337
                      value: root210
                    - id: 337
                      value: root210
                    - id: 337
                      value: root210
                    - id: 337
                      value: root210
                    - id: 337
                      value: root210
                    - id: 337
                      value: root210
                    - id: 337
                      value: root210
                status: success


        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: The detail description on the status
        results:
          type: object
          example: {<Json Object>}
          description: Json Object of returned results 
          properties:      
            created_by:
              type: string
              example: ""
              description: The detail description on the status
            date_created:
              type: string
              example: "10 jul 2019 / 08:48"
              description: The detail description on the status
            date_updated:
              type: string
              example: "10 jul 2019 / 08:48"
              description: The detail description on the status
            group_description:
              type: string
              example: "Default Consumer Group"
              description: The detail description on the status
            group_function:
              type: array
              example: [{<JSON result Object}]
              description: The list of Json result object
              items:
                type: object
                properties:                      
                    id:
                      type: integer
                      description: Index group of the document
                      example: "4574"
                    value: 
                      type: string
                      description: Content type of the document
                      example: "Market Place Screen"
            group_name:
              type: string
              example: "TEST M3 Consumer Group"
              description: The detail description on the status
            id:
              type: integer
              example: "253"
              description: The detail description on the status
            users:
              type: array
              example: [{<JSON result Object}]
              description: The list of Json result object
              items:
                type: object
                properties:                      
                    id:
                      type: integer
                      description: Index group of the document
                      example: "337"
                    value: 
                      type: string
                      description: Content type of the document
                      example: "root210"
        status:
          type: string
          example: success
          description: The status of the API call Success/Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v1.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Nov 25,2019
              description: Initial version release          
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header.
