openapi: 3.0.1
info:
  title: Org Group List
  description: Get Org group list
  x-subscribelink: org_group_list
  version: '1.0.0'
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io'
tags:
- name: "v1.0.0"
  description: "Published Date - May 21, 2021"
paths:
   /org/getorggrouplist:
    get:
      tags:
        - v1.0.0
      parameters:
        - in: query
          name: org_id
          schema:
            type: integer
          description: Organization Id
          example: 1120
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: successfully processed
                result:
                  - created_by: admin
                    date_created: 01 oct 2020 / 20:45
                    group_description: Predefined group
                    group_name: AI & Data (Individual)
                    id: 1485
                    users: 1
                  - created_by: admin
                    date_created: 01 oct 2020 / 12:45
                    group_description: Normal user access rights to download open datasets
                    group_name: Data Alliance Basic Access
                    id: 1486
                    users: 1
                status: success

        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: The detail description on the status
        results:
          type: array
          example: [{<JSON result Object}]
          description: The list of Json result object
          items:
            type: object
            properties:                      
                created_by:
                  type: string
                  description: User created by
                  example: "admin"
                date_created: 
                  type: string
                  description: User created date
                  example: "06 oct 2020 / 11:37"
                group_description: 
                  type: string
                  description: "Default consumer group "
                  example: "06 oct 2020 / 11:37"
                group_name: 
                  type: string
                  description: "Mi test group"
                  example: "06 oct 2020 / 11:37"
                id: 
                  type: integer
                  description: "user id"
                  example: "1236"
                users: 
                  type: string
                  description: users
                  example: "1"
        status:
          type: string
          example: Success
          description: The status of the API call Success/Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v1.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Nov 25,2019
              description: Initial version release          
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header.
