openapi: 3.0.1
info:
  title: Org Info
  description: Get organization information
  x-subscribelink: org_info
  version: '1.0.0'
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io'
tags:
- name: "v1.0.0"
  description: "Published Date - May 21, 2021"
paths:
   /org/getorginfo:
    get:
      tags:
        - v1.0.0
      parameters:
        - in: query
          name: org_id
          schema:
            type: integer
          description: Organization Id
          example: 1120
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: ''
                result:
                  api_key: 41CAD619434F430882E8
                  client_id: 399B4944
                  config_id: null
                  ctype: 'NO'
                  date_created: 01 oct 2020 / 21:03
                  date_updated: 01 oct 2020 / 21:03
                  description: 'contact person sritest '
                  email: sritest2@test.com
                  id: 1121
                  name: sritest2@test.com
                  org_type: child
                  public_key: ''
                  user_api_key: OaYpCkgRDn1DBbh4HGO4m4fKaX4RrX82tqepCb3d
                  user_name: admin
                status: success
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: The detail description on the status
        results:
          type: object
          example: {<Json Object>}
          description: Json Object of returned results 
          properties:
            api_key:
              type: string
              example: 41CAD6194....
              description: Organization API Key
            client_id:
              type: integer
              example: 399B4944....
              description: Organization client id
            config_id:
              type: string
              example: null
              description: Organization config id
            ctype:
              type: string
              example: NO
              description: Organization ctype
            date_created:
              type: string
              example: 01 oct 2020 / 21:03
              description: Organization created date
            date_updated:
              type: string
              example: 01 oct 2020 / 21:03
              description: Organization date updated
            description:
              type: string
              example: contact person sritest
              description: Organization description
            email:
              type: string
              example: sritest2@test.com
              description: Organization email
            id:
              type: integer
              example: 1121
              description: id
            name:
              type: string
              example: sritest2@test.com
              description: Organization name
            org_type:
              type: string
              example: child
              description: Organization type
            public_key:
              type: string
              example: ""
              description: Organization public key
            user_api_key:
              type: string
              example: OaYpCkgRDn1DBbh....
              description: Organization user api key
            user_name:
              type: string
              example: admin
              description: Organization user name
        status:
          type: string
          example: Success
          description: The status of the API call Success/Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties:
        v1.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Nov 25,2019
              description: Initial version release          
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header.
