openapi: 3.0.1
info:
  title: Refresh api key
  description: Refresh api key
  version: v0.1.0
  x-subscribelink: refresh_api_key
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - May 12, 2021"
paths:
  /org/refreshapikey:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully processed
                results:
                  id: 2196
                  new_api_key: AA6A108150A04...
                status: Success
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        results:
          type: object
          description: The result of the API call.
          example: { "<Json": "Object>" }
          properties: 
            id:
              description: id
              example: 2196
              type: integer
            new_api_key:
              description: New api key
              example: "AA6A108150A04..."
              type: string
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
        
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - May 12, 2021
                description: Initial version release    
    input:
      type: object
      required:
      
        - user_id
        - updated_by
      properties:
        user_id:
          x-name: user_id
          type: integer
          default: True
          example: 2196
          description: User id
        updated_by:
          x-name: group_id
          type: integer
          default: True
          example: 2
          description: Updated by
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
