openapi: 3.0.1
info:
  title: Subscribed Microservices
  description: Subscribed Microservices
  version: v0.1.0
  x-subscribelink: subscribed_microservices
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - May 12, 2021"
paths:
  /subscribedmicroservices:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                status: success
                message: successfully processed
                results:
                  - microservice: Date Resolution
                    calls: 57
                    spend: 0
                    class: Utility
                    doc_url: ''
                    endpoint: >-
                      https://dev-apis.sentient.io/microservices/utility/dateresolution/v0/getresults
                  - microservice: Date Resolution
                    calls: 57
                    spend: 0
                    class: Utility
                    doc_url: ''
                    endpoint: >-
                      https://dev-apis.sentient.io/microservices/utility/dateresolution/v0/getresults
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        status:
          type: string
          example: success
          description: Activity details
        message:
          type: string
          example: successfully processed
          description: Activity details
        microservice_performance:
          type: array
          example: [{<JSON result Object}]
          description: The list of Json result object
          items:
            type: object
            properties:                      
                microservice:
                  type: string
                  description: Microservice name
                  example: Date Resolution
                calls:
                  type: integer
                  format: float
                  description: Microservice total calls
                  example: 57.0
                spend:
                  type: integer
                  format: float
                  description: Microservice spend
                  example: 0.0
                class:
                  type: string
                  description: Microservice class
                  example: Utility
                doc_url:
                  type: string
                  description: Microservice document url
                  example: ""
                endpoint:
                  type: string
                  description: Microservice endpoint
                  example: https://dev-apis.sentient.io/microservices/utility/dateresolution/v0/getresults
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - May 12, 2021
                description: Initial version release    
    input:
      type: object
      required:
        - user_id
        - updated_by
      properties:
        from_date:
          x-name: from_date
          type: integer
          default: True
          example: 2021-01-01
          description: User id
        to_date:
          x-name: to_date
          type: integer
          default: True
          example: 2021-02-24
          description: User updated by
        org_id:
          x-name: to_date
          type: integer
          default: True
          example: 1
          description: User updated by
        each_function_details:
          x-name: to_date
          type: integer
          default: True
          example: WIKIPEDIA
          description: User updated by
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
