openapi: 3.0.1
info:
  title: Update Org
  description: Update org info
  version: v0.1.0
  x-subscribelink: This microservice is used to edit and update the organization details.
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - May 12, 2021"
paths:
  /org/editorg:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully processed
                results:
                  id: 2196
                  new_api_key: AA6A108150A04...
                status: Success
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        results:
          type: object
          description: The result of the API call.
          example: { "<Json": "Object>" }
          properties: 
            id:
              description: id
              example: 2196
              type: integer
            new_api_key:
              description: New api key
              example: "AA6A108150A04..."
              type: string
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - Jul 09, 2021
                description: Initial version release    
    input:
      type: object
      required:
      properties:
        org_id:
          x-name: org_id
          type: string
          example: 829
          description: Organization Id
        email:
          x-name: email
          type: string
          example: test@gmail.com
          description: Organization email
        description:
          x-name: description
          type: string
          example: "testing description"
          description: Organization description
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
