openapi: 3.0.1
info:
  title: Update user info
  description: Update user info
  version: v0.1.0
  x-subscribelink: update_user_info
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - May 12, 2021"
paths:
  /org/updateuserinfo:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: successfully processed
                results:
                  id: 2196
                status: success

        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        results:
          type: object
          description: The result of the API call.
          example: { "<Json": "Object>" }
          properties: 
            id:
              description: Sample rate of the output audio
              example: 2196
              type: integer
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: Published Date - May 12, 2021
                description: Initial version release    
    input:
      type: object
      required:
      
        - user_id
      
      properties:
        id:
          x-name: user_id
          type: string
          default: True
          example: 0
          description: |+
            Input text to be synthesised 
        org_id:
          x-name: group_id
          type: string
          default: True
          example: 1636
          description: |+
            Input text to be synthesised
        user_name:
          x-name: group_id
          type: string
          default: True
          example: test@gmail.com
          description: |+
            Input text to be synthesised
        user_password:
          x-name: group_id
          type: string
          default: True
          example: xxxxxx
          description: |+
            Input text to be synthesised
        user_signin:
          x-name: group_id
          type: string
          example: ""
          description: |+
            Input text to be synthesised
        email_address:
          x-name: group_id
          type: string
          default: True
          example: test
          description: |+
            Input text to be synthesised
        send_email:
          x-name: group_id
          type: string
          default: True
          example: yes
          description: |+
            Input text to be synthesised
        user_groups:
          x-name: group_id
          type: string
          example: []
          description: |+
            Input text to be synthesised
        date_updated:
          x-name: group_id
          type: string
          default: True
          example: 22/6/2021 @ 20:25:2
          description: |+
            Input text to be synthesised
        date_created:
          x-name: group_id
          type: string
          default: True
          example: 22/6/2021 @ 20:25:2
          description: |+
            Input text to be synthesised
        updated_by:
          x-name: group_id
          type: string
          default: True
          example: 2
          description: |+
            Input text to be synthesised
        root_user:
          x-name: group_id
          type: string
          default: True
          example: no
          description: |+
            Input text to be synthesised
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
