openapi: 3.0.1
info:
  title: Update Password
  description: This API provides detail insight into errors that may occur while performing an API call. This API shows the aspects including but limited to the number of invalid inputs, authentication failures, number of invalid requests, and API key errors for any given microservice within a specific period of time (i.e. monthly, yearly, etc.).
  version: v0.1.0
  x-subscribelink: update_password
servers:
  - url: 'https://dev-microserviceapi-org.sentient.io' 
tags:
- name: "v0.1.0"
  description: "Published Date - Sep 6, 2021"
paths:
  /org/v0/updatepassword:
    post:
      tags:
        - v0.1.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '415':
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
components:
  schemas:
    success:
      type: object
      properties:
        message:
          type: string
          example: Successfully Processed
          description: The detailed status of the api call
        status:
          type: string
          example: Success
          description: The status of the API call success/failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server error
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1.0:
          type: array
          items:
            oneOf:
              - type: string
                example: "Published Date - Sep 6, 2021"
                description: Initial version release    
    input:
      type: object
      required:
        - new_password
      properties:
        new_password:
          x-name: new_password
          type: string
          default: True
          example: "NewPassword@123"
          description: New Password to set to the user
        old_password:
          x-name: old_password
          type: string
          default: False
          example: "OldPassword@123"
          description: Old Password of the user
        user_id:
          x-name: user_id
          type: integer
          example: 2365
          description: User Id
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header.
