openapi: 3.0.1
info:
  title: Basic Individual Search Dun & Bradstreet (SG)
  description:  |+
    This Data microservice provides the information on the (Singapore-registered) business interest of an individual that includes the individual’s actual name, residential address, business and shareholding in businesses, current & previous ownership, litigation against individual and businesses, bankruptcy record and count on the times this individual has been searched on. Updated daily.
  version: '0.1'
servers:
  - url: 'https://api.sentient.io'
tags:
- name: "v0.1"
  description: "Published Date - Jul 23, 2019"
paths:
   /dnb/prod/sbis:
    post:
      tags:
        - v0.1
      summary: Adds a new user
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/REQUEST'
      responses:
        '200':
          description: success response
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/success'
              example: 
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
        type: object
        properties:
            REPORT:
              type: object
              example:
              description:  |+
                Report details with following children&#58;
                [META_INFO]
                [BASIC_INFO]
                [LIT_SEARCH_INFO]
                [LIST_CURRENT_COMP]
                [LIST_PREVIOUS_COMP]
                [LIST_BANKRUPTCY]
                [LIST_LIT]
                [LIST_LIT_DTL]
              properties:
                BASIC_INFO :
                  type: object
                  description: |+
                    Basic Information with following children&#58;
                    PA_REG_NO
                    ADDRESS1
                    ADDRESS2
                    ADDRESS3
                  example: 
                  properties:
                    PA_REG_NO :
                      type: string
                      description: Public Accountant Registration No.
                      example: "00091"
                    USER_ID :
                      type: string
                      example: N/A
                      description: Valid user id in DDP system. It is for (For internal use)
                    ADD_ADDRESS1:
                      type: string
                      description: Address Line 1
                      example: "1 HARBOURFRONT AVENUE , 18 - 01"
                    USER_ID2 :
                      type: string
                      example: N/A
                      description: Valid user id in DDP system. It is for (For internal use)
                    ADDRESS2 :
                      type: string
                      description: Address 2
                      example: "vvvvv"
                    ADDRESS3:
                      type: string
                      description: Address 3
                      example: "470137, SINGAPORE"
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    REQUEST:
      type: object
      properties:
        TOT_ITEMS:
          type: number
          example: 1
          description: Number of subjects being enquired relating to the Run
          default: false
        ENQUIRY:
          type: object
          example: |+
            <ENQUIRY><SUBJECT_IDNO>197601887E</SUBJECT_IDNO><SUBJECT_NAME>TRANSTAR TRAVEL PTE LTD</SUBJECT_NAME></ENQUIRY>
          description: Contains information of each request details
          default: true
          properties:
            SUBJECT_IDNO:
              type: string
              example: 199707714C
              description: "Subject’s ID Number (individual) or Registration Number (company/business) as captured in DDP"
              default: true
            SUBJECT_NAME:
              type: string
              example: GPS INDUSTRIES PTE LTD
              description: Subjects Name as captured in DDP
              default: false
    versions:
      type: object
      properties: 
        v0.1:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Jul 23, 2019
              description: Initial version release
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
