openapi: 3.0.1
info:
  title: Business Check Dun & Bradstreet (SG)
  description: |+
    This Data microservice provides key business information of a Singapore-registered company includes the business name, registration number, registered address and date of change, company status, registered activities, shareholders details (i.e. date of commencement, residing address) capital amount and shares allocated to each shareholders. Updated daily.
  version: '0.1'
servers:
  - url: 'https://api.sentient.io'
tags:
- name: "v0.1"
  description: "Published Date - Jul 23, 2019"
paths:
   /dnb/prod/sbc:
    post:
      tags:
        - v0.1
      summary: Adds a new user
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/REQUEST'              
      responses:
        '200':
          description: success response
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/success'
              example: |+
                <success><report><meta_info><service>string</service> <system_id>string</system_id> <creation_date>string</creation_date> <user_id>string</user_id> <class>string</class></meta_info> <req_search_info><comp_name>string</comp_name> <reg_no>string</reg_no> <req_date>string</req_date> <req_reg_no>string</req_reg_no> <req_name>string</req_name> <req_date_str>string</req_date_str></req_search_info> <registry_detail><comp_name>string</comp_name> <renewal_date>string</renewal_date> <address1>string</address1> <address2>string</address2> <address3>string</address3> <address4>string</address4> <comp_type_code>string</comp_type_code> <reg_date>string</reg_date> <reg_activity1>string</reg_activity1> <reg_activity2>string</reg_activity2> <acc_date>string</acc_date> <status_effect_date>string</status_effect_date> <name_effect_date>string</name_effect_date> <expiry_date>string</expiry_date> <comp_type>string</comp_type> <change_addr_date>string</change_addr_date> <comp_status>string</comp_status> <reg_activity_desc1>string</reg_activity_desc1> <reg_activity_desc2>string</reg_activity_desc2> <auditor>string</auditor> <auditor_appmt_date>string</auditor_appmt_date> <last_ar_date>string</last_ar_date> <last_agm_date>string</last_agm_date> <country_incorp>string</country_incorp></registry_detail> <employee_size><elements>string</elements> <amount>string</amount></employee_size> <list_biz_branch><biz_branch><addr_building>string</addr_building> <addr_postcode>string</addr_postcode> <addr_address1>string</addr_address1></biz_branch> </list_biz_branch><list_reg_charges><reg_charges><charge_no>string</charge_no> <charge_date>string</charge_date> <chargee_comp>string</chargee_comp> <currency>string</currency> <amt_secured>string</amt_secured> <status_satisfaction>string</status_satisfaction></reg_charges> </list_reg_charges><list_liquidator><liquidator><liq_name>string</liq_name> <liq_id>string</liq_id> <liq_position>string</liq_position> <liq_comp>string</liq_comp> <liq_address1>string</liq_address1> <liq_address2>string</liq_address2> <liq_address3>string</liq_address3> <liq_address4>string</liq_address4> <liq_appointment_date>string</liq_appointment_date></liquidator> </list_liquidator><list_sales_revenue_amount><sales_revenue_amount><elements>string</elements> <year>string</year> <currency>string</currency> <amount>0</amount></sales_revenue_amount></list_sales_revenue_amount><list_shareholder><shareholder><address>string</address>

                  <comp_id>string</comp_id> <no_of_share>string</no_of_share> <currency>string</currency> <shareholder_type>string</shareholder_type> <share_type>string</share_type> <shareholder_name>string</shareholder_name> <change_addr_date>string</change_addr_date> <addr_type>string</addr_type> <nationality>string</nationality></shareholder> </list_shareholder><list_share_interest_comp><share_interest_comp><comp_name>string</comp_name> <share_owned_unit>string</share_owned_unit> <share_owned_percent>string</share_owned_percent> <status>string</status></share_interest_comp></list_share_interest_comp><list_officer_owner><officer_owner><address>string</address>
                  
                  <identity_id>string</identity_id> <position>string</position> <addr_type>string</addr_type> <cessation_date>string</cessation_date> <officer_name>string</officer_name> <change_addr_date>string</change_addr_date> <appmt_date>string</appmt_date> <nationality>string</nationality></officer_owner> </list_officer_owner><list_capital><capital><capital_category>string</capital_category> <capital_type>string</capital_type> <currency>string</currency> <capital_amt>string</capital_amt> <no_of_shares>string</no_of_shares></capital> </list_capital><list_name_change><name_change><prev_name>string</prev_name> <effect_date>string</effect_date></name_change></list_name_change></report></success>
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'        
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
        type: object
        properties:
            REPORT:
              type: object
              properties:
                META_INFO:
                  type: object
                  properties:
                    SERVICE:
                      type: string
                    SYSTEM_ID :
                      type: string
                    CREATION_DATE:
                      type: string
                    USER_ID :
                      type: string
                    CLASS  :
                      type: string                      
                REQ_SEARCH_INFO  :
                  type: object
                  properties:
                    COMP_NAME  :
                      type: string
                    REG_NO :
                      type: string
                    REQ_DATE :
                      type: string
                    REQ_REG_NO :
                      type: string
                    REQ_NAME  :
                      type: string
                    REQ_DATE_STR  :
                      type: string                      
                REGISTRY_DETAIL :
                  type: object
                  properties:
                    COMP_NAME:
                      type: string
                    RENEWAL_DATE:
                      type: string
                    ADDRESS1 :
                      type: string
                    ADDRESS2  :
                      type: string
                    ADDRESS3  :
                      type: string
                    ADDRESS4:
                      type: string    
                    COMP_TYPE_CODE:
                      type: string
                    REG_DATE  :
                      type: string
                    REG_ACTIVITY1:
                      type: string
                    REG_ACTIVITY2:
                      type: string
                    ACC_DATE   :
                      type: string
                    STATUS_EFFECT_DATE:
                      type: string 
                    NAME_EFFECT_DATE:
                      type: string
                    EXPIRY_DATE :
                      type: string
                    COMP_TYPE  :
                      type: string
                    CHANGE_ADDR_DATE  :
                      type: string
                    COMP_STATUS  :
                      type: string
                    REG_ACTIVITY_DESC1   :
                      type: string 
                    REG_ACTIVITY_DESC2   :
                      type: string
                    AUDITOR  :
                      type: string
                    AUDITOR_APPMT_DATE  :
                      type: string
                    LAST_AR_DATE  :
                      type: string
                    LAST_AGM_DATE   :
                      type: string
                    COUNTRY_INCORP:
                      type: string 
                EMPLOYEE_SIZE :
                  type: object
                  properties:
                    ELEMENTS:
                      type: string
                    AMOUNT:
                      type: string
                LIST_BIZ_BRANCH :
                  type: array
                  items:
                    properties:
                      BIZ_BRANCH :
                        type: object
                        properties:
                          ADDR_BUILDING  :
                            type: string
                          ADDR_POSTCODE :
                            type: string
                          ADDR_ADDRESS1 :
                            type: string
                LIST_REG_CHARGES  :
                  type: array
                  items:
                    properties:
                      REG_CHARGES :
                        type: object
                        properties:
                          CHARGE_NO  :
                            type: string
                          CHARGE_DATE  :
                            type: string
                          CHARGEE_COMP  :
                            type: string    
                          CURRENCY   :
                            type: string
                          AMT_SECURED  :
                            type: string
                          STATUS_SATISFACTION  :
                            type: string         
                LIST_LIQUIDATOR  :
                  type: array
                  items:
                    properties:
                      LIQUIDATOR :
                        type: object
                        properties:
                          LIQ_NAME  :
                            type: string
                          LIQ_ID  :
                            type: string
                          LIQ_POSITION  :
                            type: string    
                          LIQ_COMP:
                            type: string
                          LIQ_ADDRESS1  :
                            type: string
                          LIQ_ADDRESS2  :
                            type: string  
                          LIQ_ADDRESS3:
                            type: string
                          LIQ_ADDRESS4  :
                            type: string
                          LIQ_APPOINTMENT_DATE  :
                            type: string 
                LIST_SALES_REVENUE_AMOUNT :
                  type: array
                  items:
                    properties:
                      SALES_REVENUE_AMOUNT:
                        type: object
                        properties:
                          ELEMENTS :
                            type: string
                          YEAR :
                            type: string       
                          CURRENCY :
                            type: string
                          AMOUNT:
                            type: number
                LIST_SHAREHOLDER:
                  type: array
                  items:
                    properties:
                      SHAREHOLDER:
                        type: object
                        properties:
                          ADDRESS:
                            type: string
                          COMP_ID:
                            type: string       
                          NO_OF_SHARE:
                            type: string
                          CURRENCY:
                            type: string    
                          SHAREHOLDER_TYPE:
                            type: string
                          SHARE_TYPE:
                            type: string    
                          SHAREHOLDER_NAME:
                            type: string
                          CHANGE_ADDR_DATE:
                            type: string
                          ADDR_TYPE:
                            type: string    
                          NATIONALITY:
                            type: string    
                LIST_SHARE_INTEREST_COMP :
                  type: array
                  items:
                    properties:
                      SHARE_INTEREST_COMP:
                        type: object
                        properties:
                          COMP_NAME:
                            type: string
                          SHARE_OWNED_UNIT:
                            type: string
                          SHARE_OWNED_PERCENT:
                            type: string
                          STATUS:
                            type: string
                LIST_OFFICER_OWNER :
                  type: array
                  items:
                    properties:
                      OFFICER_OWNER:
                        type: object
                        properties:
                          ADDRESS :
                            type: string
                          IDENTITY_ID :
                            type: string       
                          POSITION :
                            type: string
                          ADDR_TYPE:
                            type: string    
                          CESSATION_DATE :
                            type: string 
                          OFFICER_NAME  :
                            type: string       
                          CHANGE_ADDR_DATE :
                            type: string
                          APPMT_DATE:
                            type: string    
                          NATIONALITY :
                            type: string 
                LIST_CAPITAL:
                  type: array
                  items:
                    properties:
                      CAPITAL:
                        type: object
                        properties:
                          CAPITAL_CATEGORY:
                            type: string
                          CAPITAL_TYPE:
                            type: string       
                          CURRENCY:
                            type: string
                          CAPITAL_AMT :
                            type: string    
                          NO_OF_SHARES :
                            type: string     
                LIST_NAME_CHANGE:
                  type: array
                  items:
                    properties:
                      NAME_CHANGE:
                        type: object
                        properties:
                          PREV_NAME:
                            type: string
                          EFFECT_DATE:
                            type: string                            
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    REQUEST:
      type: object
      properties:
        TOT_ITEMS:
          type: number
          example: 1
          description: Number of subjects being enquired relating to the Run
          default: false
        ENQUIRY:
          type: object
          example: 
          description: Contains information of each request details
          default: true
          properties:
            SUBJECT_IDNO:
              type: string
              example: 199707714C
              description: Subjects ID Number (individual) or Registration
              default: true
            SUBJECT_NAME:
              type: string
              example: GPS INDUSTRIES PTE LTD
              description: Subjects Name as captured in DDP
              default: false
    versions:
      type: object
      properties: 
        v0.1:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Jul 23, 2019
              description: Initial version release
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
