openapi: 3.0.1
info:
  title: Business Check Dun & Bradstreet (SG)
  description:  This Data microservice provides key business information of a Singapore-registered company includes the business name, registration number, registered address and date of change, company status, registered activities, shareholders details (i.e. date of commencement, residing address) capital amount and shares allocated to each shareholders. Updated daily.<br><br><b>Authentication</b>:<br><br>Authentication is done using the x-api-key in the request header.<br><br>
  version: '0.1'
servers:
  - url: 'https://api.sentient.io'
tags:
- name: "v0.1"
  description: "Published Date - Jul 23, 2019"
paths:
   /dnb/prod/sbc:
    post:
      tags:
        - v0.1
      summary: Adds a new user
      requestBody:
        content:
          application/xml:
            schema:
              type: string
            examples:
              xml:
                summary: A sample XML response
                value: ''               
      responses:
        '200':
          description: success response
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/success'
              example:
                success: 
                   REPORT: 
                    META_INFO: 
                     SERVICE: string
                     SYSTEM_ID: string
                     CREATION_DATE: string
                     USER_ID: string
                     CLASS: string
                    REQ_SEARCH_INFO: 
                     COMP_NAME: string
                     REG_NO: string
                     REQ_DATE: string
                     REQ_REG_NO: string
                     REQ_NAME: string
                     REQ_DATE_STR: string
                    REGISTRY_DETAIL: 
                     COMP_NAME: string
                     RENEWAL_DATE: string
                     ADDRESS1: string
                     ADDRESS2: string
                     ADDRESS3: string
                     ADDRESS4: string
                     COMP_TYPE_CODE: string
                     REG_DATE: string
                     REG_ACTIVITY1: string
                     REG_ACTIVITY2: string
                     ACC_DATE: string
                     STATUS_EFFECT_DATE: string
                     NAME_EFFECT_DATE: string
                     EXPIRY_DATE: string
                     COMP_TYPE: string
                     CHANGE_ADDR_DATE: string
                     COMP_STATUS: string
                     REG_ACTIVITY_DESC1: string
                     REG_ACTIVITY_DESC2: string
                     AUDITOR: string
                     AUDITOR_APPMT_DATE: string
                     LAST_AR_DATE: string
                     LAST_AGM_DATE: string
                     COUNTRY_INCORP: string
                    EMPLOYEE_SIZE: 
                     ELEMENTS: string
                     AMOUNT: string
                    LIST_BIZ_BRANCH: 
                     BIZ_BRANCH: 
                      ADDR_BUILDING: string
                      ADDR_POSTCODE: string
                      ADDR_ADDRESS1: string
                    LIST_REG_CHARGES: 
                     REG_CHARGES: 
                      CHARGE_NO: string
                      CHARGE_DATE: string
                      CHARGEE_COMP: string
                      CURRENCY: string
                      AMT_SECURED: string
                      STATUS_SATISFACTION: string
                    LIST_LIQUIDATOR: 
                     LIQUIDATOR: 
                      LIQ_NAME: string
                      LIQ_ID: string
                      LIQ_POSITION: string
                      LIQ_COMP: string
                      LIQ_ADDRESS1: string
                      LIQ_ADDRESS2: string
                      LIQ_ADDRESS3: string
                      LIQ_ADDRESS4: string
                      LIQ_APPOINTMENT_DATE: string
                    LIST_SALES_REVENUE_AMOUNT: 
                     SALES_REVENUE_AMOUNT: 
                      ELEMENTS: string
                      YEAR: string
                      CURRENCY: string
                      AMOUNT: 0
                    LIST_SHAREHOLDER: 
                     SHAREHOLDER: 
                      ADDRESS: string
                      COMP_ID: string
                      NO_OF_SHARE: string
                      CURRENCY: string
                      SHAREHOLDER_TYPE: string
                      SHARE_TYPE: string
                      SHAREHOLDER_NAME: string
                      CHANGE_ADDR_DATE: string
                      ADDR_TYPE: string
                      NATIONALITY: string
                    LIST_SHARE_INTEREST_COMP: 
                     SHARE_INTEREST_COMP: 
                      COMP_NAME: string
                      SHARE_OWNED_UNIT: string
                      SHARE_OWNED_PERCENT: string
                      STATUS: string
                    LIST_OFFICER_OWNER: 
                     OFFICER_OWNER: 
                      ADDRESS: string
                      IDENTITY_ID: string
                      POSITION: string
                      ADDR_TYPE: string
                      CESSATION_DATE: string
                      OFFICER_NAME: string
                      CHANGE_ADDR_DATE: string
                      APPMT_DATE: string
                      NATIONALITY: string
                    LIST_CAPITAL: 
                     CAPITAL: 
                      CAPITAL_CATEGORY: string
                      CAPITAL_TYPE: string
                      CURRENCY: string
                      CAPITAL_AMT: string
                      NO_OF_SHARES: string
                    LIST_NAME_CHANGE: 
                     NAME_CHANGE: 
                      PREV_NAME: string
                      EFFECT_DATE: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'        
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
        type: object
        properties:
            REPORT:
              type: object
              properties:
                META_INFO:
                  type: object
                  properties:
                    SERVICE:
                      type: string
                    SYSTEM_ID :
                      type: string
                    CREATION_DATE:
                      type: string
                    USER_ID :
                      type: string
                    CLASS  :
                      type: string                      
                REQ_SEARCH_INFO  :
                  type: object
                  properties:
                    COMP_NAME  :
                      type: string
                    REG_NO :
                      type: string
                    REQ_DATE :
                      type: string
                    REQ_REG_NO :
                      type: string
                    REQ_NAME  :
                      type: string
                    REQ_DATE_STR  :
                      type: string                      
                REGISTRY_DETAIL :
                  type: object
                  properties:
                    COMP_NAME:
                      type: string
                    RENEWAL_DATE:
                      type: string
                    ADDRESS1 :
                      type: string
                    ADDRESS2  :
                      type: string
                    ADDRESS3  :
                      type: string
                    ADDRESS4:
                      type: string    
                    COMP_TYPE_CODE:
                      type: string
                    REG_DATE  :
                      type: string
                    REG_ACTIVITY1:
                      type: string
                    REG_ACTIVITY2:
                      type: string
                    ACC_DATE   :
                      type: string
                    STATUS_EFFECT_DATE:
                      type: string 
                    NAME_EFFECT_DATE:
                      type: string
                    EXPIRY_DATE :
                      type: string
                    COMP_TYPE  :
                      type: string
                    CHANGE_ADDR_DATE  :
                      type: string
                    COMP_STATUS  :
                      type: string
                    REG_ACTIVITY_DESC1   :
                      type: string 
                    REG_ACTIVITY_DESC2   :
                      type: string
                    AUDITOR  :
                      type: string
                    AUDITOR_APPMT_DATE  :
                      type: string
                    LAST_AR_DATE  :
                      type: string
                    LAST_AGM_DATE   :
                      type: string
                    COUNTRY_INCORP:
                      type: string 
                EMPLOYEE_SIZE :
                  type: object
                  properties:
                    ELEMENTS:
                      type: string
                    AMOUNT:
                      type: string
                LIST_BIZ_BRANCH :
                  type: array
                  items:
                    properties:
                      BIZ_BRANCH :
                        type: object
                        properties:
                          ADDR_BUILDING  :
                            type: string
                          ADDR_POSTCODE :
                            type: string
                          ADDR_ADDRESS1 :
                            type: string
                LIST_REG_CHARGES  :
                  type: array
                  items:
                    properties:
                      REG_CHARGES :
                        type: object
                        properties:
                          CHARGE_NO  :
                            type: string
                          CHARGE_DATE  :
                            type: string
                          CHARGEE_COMP  :
                            type: string    
                          CURRENCY   :
                            type: string
                          AMT_SECURED  :
                            type: string
                          STATUS_SATISFACTION  :
                            type: string         
                LIST_LIQUIDATOR  :
                  type: array
                  items:
                    properties:
                      LIQUIDATOR :
                        type: object
                        properties:
                          LIQ_NAME  :
                            type: string
                          LIQ_ID  :
                            type: string
                          LIQ_POSITION  :
                            type: string    
                          LIQ_COMP:
                            type: string
                          LIQ_ADDRESS1  :
                            type: string
                          LIQ_ADDRESS2  :
                            type: string  
                          LIQ_ADDRESS3:
                            type: string
                          LIQ_ADDRESS4  :
                            type: string
                          LIQ_APPOINTMENT_DATE  :
                            type: string 
                LIST_SALES_REVENUE_AMOUNT :
                  type: array
                  items:
                    properties:
                      SALES_REVENUE_AMOUNT:
                        type: object
                        properties:
                          ELEMENTS :
                            type: string
                          YEAR :
                            type: string       
                          CURRENCY :
                            type: string
                          AMOUNT:
                            type: number
                LIST_SHAREHOLDER:
                  type: array
                  items:
                    properties:
                      SHAREHOLDER:
                        type: object
                        properties:
                          ADDRESS:
                            type: string
                          COMP_ID:
                            type: string       
                          NO_OF_SHARE:
                            type: string
                          CURRENCY:
                            type: string    
                          SHAREHOLDER_TYPE:
                            type: string
                          SHARE_TYPE:
                            type: string    
                          SHAREHOLDER_NAME:
                            type: string
                          CHANGE_ADDR_DATE:
                            type: string
                          ADDR_TYPE:
                            type: string    
                          NATIONALITY:
                            type: string    
                LIST_SHARE_INTEREST_COMP :
                  type: array
                  items:
                    properties:
                      SHARE_INTEREST_COMP:
                        type: object
                        properties:
                          COMP_NAME:
                            type: string
                          SHARE_OWNED_UNIT:
                            type: string
                          SHARE_OWNED_PERCENT:
                            type: string
                          STATUS:
                            type: string
                LIST_OFFICER_OWNER :
                  type: array
                  items:
                    properties:
                      OFFICER_OWNER:
                        type: object
                        properties:
                          ADDRESS :
                            type: string
                          IDENTITY_ID :
                            type: string       
                          POSITION :
                            type: string
                          ADDR_TYPE:
                            type: string    
                          CESSATION_DATE :
                            type: string 
                          OFFICER_NAME  :
                            type: string       
                          CHANGE_ADDR_DATE :
                            type: string
                          APPMT_DATE:
                            type: string    
                          NATIONALITY :
                            type: string 
                LIST_CAPITAL:
                  type: array
                  items:
                    properties:
                      CAPITAL:
                        type: object
                        properties:
                          CAPITAL_CATEGORY:
                            type: string
                          CAPITAL_TYPE:
                            type: string       
                          CURRENCY:
                            type: string
                          CAPITAL_AMT :
                            type: string    
                          NO_OF_SHARES :
                            type: string     
                LIST_NAME_CHANGE:
                  type: array
                  items:
                    properties:
                      NAME_CHANGE:
                        type: object
                        properties:
                          PREV_NAME:
                            type: string
                          EFFECT_DATE:
                            type: string                            
    unauthorized:
      type: object
      items:
        properties:
          message:
            type: string
            example: Missing Authentication Token
          status:
            type: string
            example: Failure
    forbidden:
      type: object
      items:
        properties:
          message:
            type: string
            example: Access Denied Unauthorized User
          status:
            type: string
            example: Failure
    paymentrequired:
      type: object
      items:
        properties:
          message:
            type: string
            example: Insufficient Credits Kindly Top Up
          status:
            type: string
            example: Failure
    notfound:
      type: object
      items:
        properties:
          message:
            type: string
            example: Invalid Request URL
          status:
            type: string
            example: Failure
    servererror:
      type: object
      items:
        properties:
          message:
            type: string
            example: Internal Server Error
          status:
            type: string
            example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Jul 23, 2019
              description: Initial version release
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
