openapi: 3.0.1
info:
  title: Directory of Singapore Startups
  description: |+
    This Data microservice retrieves the list of all Singapore startup companies found on the internet through web scraping. Updated quarterly.
  x-additionalinfo: |+
    **Search Types**
    
    All values have to be URL encoded
    
    **Keyword search**
    
    Keyword search; search for all searchable fields
    
    **Using querystring:**
    
    > e27 Or AAR Consultancy
    
    **Filter search**
    
    **Example 1:** Get all results except ang mo kio 
    
    Using fiterdata:
    
    > {"must_not":[{"match":{"name":"Nityo Progression Consultancy Pte Ltd"}}]}
    
    Or
    
    Using querystring:
    
    > name:"Nityo Progression Consultancy Pte Ltd"
    
    **Example 2:** Filter results with shopname match phase “ang mo supermarket” and street match bishan
    
    Using fiterdata:
    
    > {"filter":[{"match":{"type":"company"}},{"match":{"name":"AAR Consultancy"}}]}
    
    **<b>Supported Filter Types:**
   
    **must** - All of these clauses must match. The equivalent of AND.
    
    **must_not** - All of these clauses must not match. The equivalent of NOT.
    
    **should** - At least one of these clauses must match. The equivalent of OR.
    
    **filter** - Clauses that must match, but are run in non-scoring, filtering mode.
    
    **Supported Match Types:**
    
    **match** - is to search within a full-text field for a single word
    
    > { "match":{"address":"singapore"}}
    
    **match_phrase** - is to search a full text field
    
    > { "match_phrase":{ "address":singapore"}}
    
    **match_phrase_prefix** - is to search a full text field with prefix
    
    > {"match_phrase_prefix":{"address":"singapore"}}
    
    **term** - returns documents that contain one or more exact terms in a provided field.
    
    > {"term":{"address":"singapore"}}
    
    **terms** - The terms query is the same as the term query, except you can search for multiple values.
    
    > {"terms":{"address":["singapore","ang mo kio"]}}
    
    **Sample filterdata JSON:**
    > {
    "must":[{"match_phrase":{"address":"singapore"}}],
    "filter":[{"match":{"source":"sentient"}}],
    "should":[{"match":{"type":"company"}}],
    "must_not":[{"match":{"name":"Nityo Progression Consultancy Pte Ltd"}}
    }
  version: '0.1'
servers:
  - url: 'https://api.sentient.io'
tags:
- name: "v0.1"
  description: "Published Date - Nov 15, 2019"
paths:
   /DaaS/prod/directories/searchdir:
    get:
      tags:
        - v0.1
      parameters:
        - in: query
          name: querystring
          schema:
            type: string
          description: keyword match to all searchable fields
          required: true
        - in: query
          name: offset
          schema:
            type: integer
            example: "0"
          description: Offset value of the resultset
          required: false
        - in: query
          name: limit
          schema:
            type: integer
            example: 10
          description: Number of records to return
          required: false
        - in: query
          name: filterdata
          schema:
            type: string
          description: Additional filter {"must":[ ],"should":[ ],"must_not":[ ],"filter":[ ]}
          required: false
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                results:
                  total: 986
                  max_score: 1
                  hits:
                  - _index: sentient_directory_index
                    _type: dir_doc
                    _id: TrrmAWgBv3dNEHq24P-C
                    _score: 1
                    _source:
                      type: company
                      source: sentient
                      address: singapore
                      createddate: '2018-12-31'
                      name: AAR Consultancy
                      logo:
                        e27: https://e27.co/img/startups/11448/logo.png
                      company:
                        e27:
                          sourceurl: https://e27.co/startup/aar-consultancy
                          type: startup
                          technology:
                          - Enterprise Solution
                          - Big Data
                          - E-commerce
                          - Education
                          - Internet of Things
                      socialmedia:
                        e27:
                          linkedin: https://sg.linkedin.com/in/soumikch
                      descshort:
                        e27: Google Certified Professionals. Providing with Consultation, Implementation
                          Strategy and Training of various online platforms, methods and campaigns,
                          including eComm launches.
                      desclong:
                        e27: 'My name is Soumik and I am founder of AAR Consultancy, a registered
                          business in Singapore. I provide online consultancy, implementation strategy
                          development and Training.I offer various online services, which you can
                          see from my attached company profile. I am an MBA with 11+ years experience
                          helping manage digital / online marketing for various industries. Been guest
                          speakers at seminars and conferences and provided corporate training to
                          SMEs and MNCs alike. I have worked with Streetdirectory, MDIS, Ogilvy and
                          Mather, American Express and Mothercare and has helped clients such as IBM,
                          Unilever, Nestle, SingTel, Guinness amongst others. SMEs, MNCs : B2B and
                          B2C.Have launched eCommerce Platforms, websites, strategies, technologies,
                          apps, and more.Trained and implemented, SEO, AdWords - ppc, media ads, social,
                          community management and more.'
                      website:
                        e27: http://ww.aaronline.sg
                      status:
                        e27: active
                message: Successfully Processed
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties:
        results:
          type: object
          properties:
            total:
              type: number
              example: 986
              description: Total number of records
            max_score:
              type: number
              example: 1
              description: The highest score value
            hits:
              type: array
              items:
                type: object
                properties:
                  _index:
                    type: string
                    description: Index group of the document
                    example: "sentient_directory_index"
                  _type: 
                    type: string
                    description: Content type of the document
                    example: "dir_doc"
                  _id: 
                    type: string
                    description: Document ID
                    example: "TrrmAWgBv3dNEHq24P-C"
                  _score: 
                    type: string
                    description: The document score for the search request
                    example: 1
                  _source: 
                    properties:
                            type: 
                              type: string
                              description: Content type of the document. Rented/Owner
                              example: company
                            source: 
                              type: string
                              description: Holds all the document details
                              example: sentient
                            address: 
                              type: string
                              description: Full address for the record
                              example: singapore
                            createddate: 
                              type: string
                              description: Record created date
                              example: '2018-12-31'
                            name: 
                              type: string
                              description: Business name
                              example: AAR Consultancy
                            logo:
                              properties:
                                e27: 
                                  type: string
                                  description: logo url
                                  example: 'https://e27.co/img/startups/11448/logo.png'
                            company:
                              properties:
                                e27:
                                  properties:
                                    sourceurl: 
                                      type: string
                                      description: record by company source url
                                      example: 'https://e27.co/startup/aar-consultancy'
                                    type: 
                                      type: string
                                      description: type of company 
                                      example: startup
                                    technology:
                                      type: array
                                      items:
                                        oneOf:
                                        - type: string
                                          format: list
                                          example: Enterprise Solution
                                        - type: string
                                          format: list
                                          example: Big Data
                                        - type: string
                                          format: list
                                          example: E-commerce
                                        - type: string
                                          format: list
                                          example: Education
                                        - type: string
                                          format: list
                                          example: Internet of Things
                            socialmedia:
                              properties:
                                e27:
                                  properties:
                                    linkedin: 
                                      type: string
                                      description: Social media  information of the record
                                      example: 'https://sg.linkedin.com/in/soumikch'
                            descshort:
                              properties:
                                e27: 
                                  type: string
                                  description: Short description
                                  example: 'Google Certified Professionals. Providing with Consultation, Implementation Strategy and Training of various online platforms, methods and campaigns, including eComm launches.'
                            desclong:
                              properties:
                                e27: 
                                  type: string
                                  description: Long description
                                  example: 'My name is Soumik and I am founder of AAR Consultancy, a registered business in Singapore. I provide online consultancy, implementation strategy development and Training.I offer various online services, which you can see from my attached company profile. I am an MBA with 11+ years experience helping manage digital / online marketing for various industries. Been guest speakers at seminars and conferences and provided corporate training to SMEs and MNCs alike. I have worked with Streetdirectory, MDIS, Ogilvy and Mather, American Express and Mothercare and has helped clients such as IBM, Unilever, Nestle, SingTel, Guinness amongst others. SMEs, MNCs : B2B and B2C.Have launched eCommerce Platforms, websites, strategies, technologies, apps, and more.Trained and implemented, SEO, AdWords - ppc, media ads, social, community management and more.'
                            website:
                              properties:
                                e27:
                                  type: string
                                  description: Website address
                                  example: 'http://ww.aaronline.sg'
                            status:
                              properties:
                                e27:
                                  type: string
                                  description: Company status
                                  example: active
        message:
          type: string
          example: Successfully Processed
        status:
          type: string
          example: Success
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.1:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Oct 10,2019
              description: Initial version release
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header.
