openapi: 3.0.1
info:
  title: Named-Entity Recognition JAP Updated
  description: |+
    This NLP microservice locates and classifies the named-entities classes from input unstructured Japanese text.
    
    The named-entity classes extracted are persons, locations, organisations and miscellaneous.
    
    This microservice automatically extracts structured information from unstructured text data such as chatlogs, emails, news articles, etc.
  version: '1.0'
servers:
  - url: 'https://apis.sentient.io'
tags:
- name: "v1.0"
  description: "Published Date - May 19, 2020"
paths:
  /microservices/nlp/japanesener/v1.0/getpredictions:
    post:
      tags:
        - v1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                results:
                  age:
                  - '56'
                  countx_other:
                  - 2稿
                  - 8口
                  doctrine_method_other:
                  - 険所コホ特室りょ
                  n_event:
                  - 受1
                  numex_other:
                  - 百経
                  ordinal_number:
                  - 30弾
                  person:
                  - くぼ
                  - 壮
                  - 琢紫
                  - ナユ
                  product_other:
                  - 都合ヘラアニ限
                  - 議帳
                  show_organization:
                  - 左成相態
                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties: 
        Company:
          x-name: Company
          type: array
          example: [ 和歌山製鉄所 ]
          description: name of Company found in the text string    
        Date:
          x-name: Date
          type: array
          example: [ 7日,2023年9月,22年9月 ]
          description: name of Date found in the text string
        Domestic_Region:
          x-name: Domestic_Region
          type: array
          example: [ 呉製鉄所 ]
          description: name of Domestic_Region found in the text string    
        Material:
          x-name: Material
          type: array
          example: [ 鉄鋼最大手 ]
          description: name of Material found in the text string              
        message:
          type: string
          example: Successfully Processed
          description: Detail description on the API status
        status:
          type: string
          example: Success
          description: The status of the API call success/failure       
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure 
    versions:
      type: object
      properties: 
        v1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - May 19,2020
              description: Updated version release v1.0
        v0.1:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - May 19,2020
              description: Initial version release
    input:
      type: object
      required:
        - text
      properties:
        text:
          x-name: text
          type: string
          default: true
          example: 30弾ソイキ昇機マ了映だ店原いひ険所コホ特室りょくぼ都合ヘラアニ限2稿タチケア迷芸歌セ利講ルねひ詳績めかをぶ観提メエ府木ホフタ分不写ひフ妹検らし器増壮憶クわ。8口アユ琢紫ヨ理特ゆほス見百経イス図退ナユ介精しぜ議帳モテ受1中コハ載北早ぎのりや載裁風力壌ひろふ。運56済ぞ下写報スや来際おっはの学要ヘ手米真社つみよや非央で野館き肉待づぜフ次睡ルをが左成相態万えやろ。
          description: |+
            Input text
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
